### ISSUE TITLE
Formateo de la tabla roto en apps y old.reddit.com

### ISSUE THREAD

**Issue by fedecalendino** [marcosmarp/dolar-bot#6]
Buenas de nuevo!

Estaba viendo que el formateo de la tabla se rompe cuando navegas en otras apps (como Apollo en iOS) o en https://old.reddit.com

<img width="891" alt="Screen Shot 2021-10-31 at 13 17 16" src="https://user-images.githubusercontent.com/7383708/139582948-8734d541-5645-434a-85e8-7ef05455d945.png">

El problema esta acá: https://github.com/marcosmarp/dolar-bot/blob/090d1b08546ad6abdb80d2f55a9d4244b465cd5e/functions.py#L74

El formato correcto para que funcione deberia ser así:

```
  Divisa | Compra | Venta
  :--- | :--- | :---
  **Oficial** | ARS{0} | ARS{1}
  **Blue** | ARS{2} | ARS{3}
  **MEP/Bolsa** | ARS{4} | ARS{5}
  **CCL** | ARS{6} | ARS{7}
  **Solidario** (+30%) | \- | ARS{8}
  **Tarjeta** (+64%) | \- | ARS{9}
```

y [acá](https://github.com/marcosmarp/dolar-bot/blob/090d1b08546ad6abdb80d2f55a9d4244b465cd5e/functions.py#L115) debería ser:

```
  Divisa | ARS$ | USD$
  :--- | :--- | :---
  **BTC** | ARS${0} | USD${1}
  **ETH** | ARS${2} | USD${3}
  **BNB** | ARS${4} | USD${5}
  **USDT** | ARS${6} | USD${7}
  **ADA** | ARS${8} | USD${9}
  **SOL** | ARS${10} | USD${11}
  **XRP** | ARS${12} | USD${13}
  **DOT** | ARS${14} | USD${15}
  **DOGE** | ARS${16} | USD${17}
  **SHIB (x1000)** | ARS${18} | USD${19}
```

------

Nota al costado: para ambos casos capaz lo que quede más limpio es armar la tabla con un for:

```python
table = [
    "Divisa | ARS$ | USD$",
    ":--- | :--- | :---",
]

for divisa, ars, usd in get_cripto_values():
    table.append(f"**{divisa}**| ARS${ars} | USD${usd} |")
    
table = "\n".join(table)
print(table)
```

`get_cripto_values` deberia devolver algo de la forma `[("BTC", 123, 123), ("ADA", 456, 456)]` para que el for funcione.

**Comment by emmandyar** [comment]
Confirmo, Red Reader la muestra así: ![Screenshot_20211031-143513-672](https://user-images.githubusercontent.com/23064809/139595294-40fde599-20b4-4c35-abbe-b734f68a416e.png)

**Comment by elivinsky** [comment]
Lo mismo pasa con Sync. 
![Screenshot_20211107-135243_Sync](https://user-images.githubusercontent.com/11669061/140654215-3012b3f2-5e21-4f4b-9de8-12df28113984.png)

**Comment by marcosmarp** [comment]
Solucionado en [commit 3c729984c793c0158a62f905adbdbc4238e92037](https://github.com/marcosmarp/dolar-bot/commit/3c729984c793c0158a62f905adbdbc4238e92037)
